### ISSUE TITLE
 The util module is missing two functions.

### ISSUE THREAD

**Issue by losehu** [wcy-cs/FishFSRNet#14]
Traceback (most recent call last):
  File "/home/jyp/FishFSRNet-main/parsing/test_parsingnet.py", line 14, in <module>
    print(util.get_parameter_number(net))
AttributeError: module 'util' has no attribute 'get_parameter_number'

{'Total': 594371, 'Trainable': 594371}
Traceback (most recent call last):
  File "/home/jyp/FishFSRNet-main/parsing/test_parsingnet.py", line 27, in <module>
    timer_test = util.timer()
AttributeError: module 'util' has no attribute 'timer'

**Comment by wcy-cs** [comment]
Thank you for your reminder. We have made the modification.
